### ISSUE TITLE
Errors when importing, running examples/benchmarks

### ISSUE THREAD

**Issue by ar4** [opesci/devito#213]
I have installed devito (devito==2.0.1+378.gf88a31d) as described in the README: `pip install --user git+https://github.com/opesci/devito.git`. No errors during installation.

`import devito` results in: `ImportError: No module named 'devito.dse'`

`python examples/benchmark.py test -P tti -a -d 20 20 20 -n 5` (taken from .travis.yml) results in: `ValueError: unable to map dtype 'int64'`

`python example_diffusion.py run -m numpy devito --spacing 0.001 --timesteps 500` in the `examples/diffusion/` directory results in `ImportError: No module named 'devito.dse'`

Running `example_diffusion.py` from the base directory of the project (rather than `examples/diffusion/`) runs successfully.

**Comment by mlange05** [comment]
@ar4 Thank you for this bug report. I have fixed the pip install to avoid the `ImportError` in master. Can you please try again and let me know if this works now?

**Comment by ar4** [comment]
@mlange05 I confirm that the import errors are now resolved. Thank you. The `ValueError: unable to map dtype 'int64'` persists, however.

**Comment by navjotk** [comment]
@ar4 Could you please post the complete output of the run that produces the `ValueError`? Thanks!

**Comment by ar4** [comment]
Out of `python examples/benchmark.py test -P tti -a -d 20 20 20 -n 5`:

```
DSE: (<filter object at 0xb3fa328c>)  --> (<filter object at 0xb41448ac>)  --> (<filter object at 0xb3fa328c>)  --> (<filter object at 0xb41448ac>)  [3.10 s]
Traceback (most recent call last):
  File "examples/benchmark.py", line 147, in <module>
    _, _, _, res = run(**params)
  File "/home/alanr/Downloads/devito/examples/tti/tti_example.py", line 79, in run
    compiler=compiler, legacy=legacy)
  File "/home/alanr/Downloads/devito/examples/tti/TTI_codegen.py", line 108, in Forward
    at.auto_tune_blocks(self.s_order + 1, self.s_order * 4 + 2)
  File "/home/alanr/Downloads/devito/devito/at_controller.py", line 135, in auto_tune_blocks
    times.append((block, self.get_execution_time()))
  File "/home/alanr/Downloads/devito/devito/at_controller.py", line 166, in get_execution_time
    self.op.propagator.run(self.op.get_args(), verbose=False)
  File "/home/alanr/Downloads/devito/devito/propagator.py", line 138, in run
    f = self.cfunction
  File "/home/alanr/Downloads/devito/devito/propagator.py", line 217, in cfunction
    self._lib = jit_compile_and_load(self.ccode, self.basename,
  File "/home/alanr/Downloads/devito/devito/propagator.py", line 203, in ccode
    self._ccode = str(manager.generate())
  File "/home/alanr/.local/lib/python3.5/site-packages/cgen/__init__.py", line 80, in __str__
    return "\n".join(l.rstrip() for l in self.generate())
  File "/home/alanr/.local/lib/python3.5/site-packages/cgen/__init__.py", line 80, in <genexpr>
    return "\n".join(l.rstrip() for l in self.generate())
  File "/home/alanr/.local/lib/python3.5/site-packages/cgen/__init__.py", line 1019, in generate
    for line in c.generate():
  File "/home/alanr/.local/lib/python3.5/site-packages/cgen/__init__.py", line 923, in generate
    for f_line in self.fdecl.generate(with_semicolon=False):
  File "/home/alanr/.local/lib/python3.5/site-packages/cgen/__init__.py", line 92, in generate
    tp_lines, tp_decl = self.get_decl_pair()
  File "/home/alanr/.local/lib/python3.5/site-packages/cgen/__init__.py", line 362, in get_decl_pair
    ", ".join(ad.inline() for ad in self.arg_decls)))
  File "/home/alanr/.local/lib/python3.5/site-packages/cgen/__init__.py", line 362, in <genexpr>
    ", ".join(ad.inline() for ad in self.arg_decls)))
  File "/home/alanr/.local/lib/python3.5/site-packages/cgen/__init__.py", line 115, in inline
    tp_lines, tp_decl = self.get_decl_pair()
  File "/home/alanr/.local/lib/python3.5/site-packages/cgen/__init__.py", line 133, in get_decl_pair
    return [dtype_to_ctype(self.dtype)], self.name
  File "/home/alanr/.local/lib/python3.5/site-packages/cgen/__init__.py", line 73, in dtype_to_ctype
    raise ValueError("unable to map dtype '%s'" % dtype)
ValueError: unable to map dtype 'int64'
```

**Comment by navjotk** [comment]
@ar4 I have been unable to reproduce this error so far. We suspect it might be because of an outdated installation of `cgen`. Could you try updating your installation of `cgen` with `pip install --upgrade cgen`?

**Comment by ar4** [comment]
`pip install --upgrade cgen` reports that cgen, and all dependencies, are already up-to-date.

Perhaps it is because I am using a 32-bit processor? Some details:

```
CPython 3.5.2
IPython 4.2.0

compiler   : GCC 4.4.7 20120313 (Red Hat 4.4.7-1)
system     : Linux
release    : 4.4.0-71-generic
machine    : i686
processor  : i686
CPU cores  : 1
interpreter: 32bit
```

**Comment by navjotk** [comment]
@ar4 The change that is expected to fix this is now in master. Could you please update your copy of the code and see if it works for you now?

**Comment by ar4** [comment]
I confirm that it now works. Many thanks!
