### ISSUE TITLE
yask: TypeError: in method 'yk_grid_set_elements_in_slice'

### ISSUE THREAD

**Issue by tjb900** [opesci/devito#413]
Code attached.

Output:
```
(devito) [timb@pnod0334 bug_20171114_yask_setelements]$ KMP_DUPLICATE_LIB_OK=TRUE DEVITO_BACKEND=yask DEVITO_LOGGING=DEBUG DEVITO_ARCH=intel KMP_AFFINITY=compact DEVITO_OPENMP=1 OMP_NUM_THREADS=256 ./bug.py
YASK: Backend initialization...
YASK: Backend successfully initialized!
DSE: extract_time_invariants [flops: 47, elapsed: 0.04] >>
     eliminate_inter_stencil_redundancies [flops: 47, elapsed: 0.04] >>
     eliminate_intra_stencil_redundancies [flops: 47, elapsed: 0.08] >>
     factorize [flops: 47, elapsed: 0.15] >>
     finalize [flops: 62, elapsed: 0.02]
     [Total elapsed: 0.33 s]
YASK: Specializing a Devito Operator for YASK...
OMP: Warning #181: OMP_PLACES: ignored because KMP_AFFINITY has been defined
YASK: Context successfully created!
YASK: Missing handler in Devito-YASK translation
YASK: Unable to offload a candidate tree.
YASK: Specialization successfully performed!
DLE: avoid_denormals [elapsed: 0.00] >>
     ompize [elapsed: 0.06]
     [Total elapsed: 0.06 s]
YASK: Context successfully created!
YASK: Allocating YaskGrid for vp ((1001, 301, 500))
YASK: YaskGrid: Setting block to given scalar via index [slice(None, None, None)]
YASK: YaskGrid: Setting full-array/block via index [slice(None, None, None)]
Traceback (most recent call last):
  File "./bug.py", line 69, in <module>
    fvp.data[:] = vp.resample(box_xy, box_z)
  File "/d/home/timb/2017/devito/devito/yask/wrappers.py", line 98, in __setitem__
    self.grid.set_elements_in_slice(val, start, stop)
TypeError: in method 'yk_grid_set_elements_in_slice', argument 2 of type '(void* buffer_ptr, SIZE)'
```
[bug.py.txt](https://github.com/opesci/devito/files/1471685/bug.py.txt)

**Comment by tjb900** [comment]
So I'm pretty sure I could work around this by providing a simple numpy array of the right size - but that's actually what resample should have been returning in this case anyway.

Was going to close it, but I'll investigate further.

**Comment by ggorman** [comment]
YASK backend currently passing all tests. If it is still failing then resubmit with failing tests.
