### ISSUE TITLE
bug in operator creation when array only used as index

### ISSUE THREAD

**Issue by tjb900** [opesci/devito#505]
```
from devito import Grid, Function, Operator, Eq, Dimension
import numpy as np

grid = Grid(shape=(10,10))
x, y = grid.dimensions

p_poke = Dimension('p_src')
d = Dimension('d')

npoke = 1

u = Function(name='u', grid=grid, space_order=0) 

coordinates = Function(name='coordinates',
    dimensions=(p_poke, d),
    shape=(npoke, grid.dim), space_order=0, dtype=np.int32)

coordinates.data[0,0] = 4
coordinates.data[0,1] = 3

poke_eq = Eq(u.indexed[coordinates.indexed[p_poke,0],
                       coordinates.indexed[p_poke,1]], 1.0)

op = Operator(poke_eq)
print(op)

# The need for the p_src_e=2 is, I think, another issue
op.apply(p_src_e=2)

print(u.data)
```

Errors with:

```
Traceback (most recent call last):
  File "indexed_as_index_bug.py", line 24, in <module>
    print(op)
  File ".../devito/ir/iet/nodes.py", line 103, in __str__
    return str(self.ccode)
  File ".../devito/ir/iet/nodes.py", line 77, in ccode
    return CGen().visit(self)
  File ".../devito/tools.py", line 544, in visit
    return meth(o, *args, **kwargs)
  File ".../devito/ir/iet/visitors.py", line 290, in visit_Operator
    decls = self._args_decl(params)
  File ".../devito/ir/iet/visitors.py", line 146, in _args_decl
    if i.is_Object:
AttributeError: 'Symbol' object has no attribute 'is_Object'
```

It all starts to work if I use the coordinates array in a numerical expression, rather than only as an index.

e.g.:
```
-poke_eq = Eq(u.indexed[coordinates.indexed[p_poke,0], coordinates.indexed[p_poke,1]], 1.0)
+poke_eq = Eq(u.indexed[coordinates.indexed[p_poke,0], coordinates.indexed[p_poke,1]], coordinates.indexed[p_poke,0]*1e-20 + 1.0)
```

giving, as desired:
```
[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]
```

**Comment by mloubout** [comment]
Does it also break without indexed? like:
`poke_eq = Eq(u.subs({u.indices[0] : coordinates.subs({d:0}), u.indices[1] : coordinates.subs({d:1})), 1.0)`

**Comment by tjb900** [comment]
Well, it does produce C code at least...  but then it's a different issue:

```
  gettimeofday(&start_section_0, NULL);
  for (int p_src = p_src_s; p_src < p_src_e - 1; p_src += 1)
  {
    // Not supported in C:
// coordinates
// coordinates
u[coordinates(p_src, 0)][coordinates(p_src, 1)] = 1.00000000000000F;
  }
  gettimeofday(&end_section_0, NULL);
  timers->section_0 += (double)(end_section_0.tv_sec-start_section_0.tv_sec)+(double)(end_section_0.tv_usec-start_section_0.tv_usec)/1000000;
  return 0;
}
```

**Comment by tjb900** [comment]
I tried a lot of ways to get it to work, trying to duplicate stuff from SparseFunction, and eventually realised that SparseFunction works because the value of the coordinate is also used on the rhs of the expression.
