### ISSUE TITLE
Automatic detection of flow with mixed save/nosave time functions

### ISSUE THREAD

**Issue by mloubout** [opesci/devito#513]
So a small bug that turned out trying to save one of the fields in `born`, 

```
from devito import *
grid = Grid((10, 10))
u1 = TimeFunction(name="u1", grid=grid, save=10, time_order=1)
u2 = TimeFunction(name="u2", grid=grid, time_order=2)
u1 = TimeFunction(name="u1", grid=grid, save=10, time_order=2)
op = Operator([Eq(u1.forward, u1 + 2.0 - u1.backward), Eq(u2.forward, u2 + 2*u2.backward -  u1.dt2)])
```

Fails to detect the flow direction

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/nethome/mlouboutin3/Dropbox/London/CodeGen/devito/devito/backends.py", line 75, in __call__
    return t(*args, **kwargs)
  File "/nethome/mlouboutin3/Dropbox/London/CodeGen/devito/devito/core/operator.py", line 54, in __new__
    obj.__init__(*args, **kwargs)
  File "/nethome/mlouboutin3/Dropbox/London/CodeGen/devito/devito/operator.py", line 82, in __init__
    clusters = clusterize(expressions)
  File "/nethome/mlouboutin3/Dropbox/London/CodeGen/devito/devito/ir/clusters/algorithms.py", line 232, in clusterize
    flowmap = detect_flow_directions(g)
  File "/nethome/mlouboutin3/Dropbox/London/CodeGen/devito/devito/ir/support/utils.py", line 98, in detect_flow_directions
    for k, v in mapper.items() if k.is_Stepping)
AssertionError
```

**Comment by FabioLuporini** [comment]
any chance this gets fixed by #509 **and** #504 ?

**Comment by mloubout** [comment]
Possibly, still checking, will let you know.

**Comment by mloubout** [comment]
I've tracked part of the problem and on it. There is two issues

- `self.parameter` are incorrect in the case above with `t` or `time` staying in it
- modulo indices are not replaced (t0, t1, t2) are never created and replaced.

I'll keep digging. (also found another issue that I need to file separately as time invariant are duplicated in some cases but need to create a simple test/example to work on it).

**Comment by mloubout** [comment]
Even though the flow is detected, I reopen the issue as the generated code is not valid for the example above
```
#define _POSIX_C_SOURCE 200809L
#include "stdlib.h"
#include "math.h"
#include "sys/time.h"
#include "xmmintrin.h"
#include "pmmintrin.h"

struct profile
{
  double section_0;
} ;


int Kernel(const float dt, float *restrict u1_vec, float *restrict u2_vec, void *_t, const int time_e, const int time_s, void *_timers, const int x_e, const int x_s, const int x_size, const int y_e, const int y_s, const int y_size)
{
  float (*restrict u1)[x_size][y_size] __attribute__((aligned(64))) = (float (*)[x_size][y_size]) u1_vec;
  float (*restrict u2)[x_size][y_size] __attribute__((aligned(64))) = (float (*)[x_size][y_size]) u2_vec;
  struct profile *timers = (struct profile*) _timers;
  /* Flush denormal numbers to zero in hardware */
  _MM_SET_DENORMALS_ZERO_MODE(_MM_DENORMALS_ZERO_ON);
  _MM_SET_FLUSH_ZERO_MODE(_MM_FLUSH_ZERO_ON);
  for (int time = time_s + 1; time < time_e - 1; time += 1)
  {
    struct timeval start_section_0, end_section_0;
    gettimeofday(&start_section_0, NULL);
    #pragma omp parallel
    {
      #pragma omp for schedule(static)
      for (int x = x_s; x < x_e; x += 1)
      {
        #pragma omp simd
        for (int y = y_s; y < y_e; y += 1)
        {
          u1[time + 1][x][y] = u1[time][x][y] - u1[time - 1][x][y] + 2.0F;
          u2[t + 1][x][y] = -(u1[time - 1][x][y]/pow(dt, 2) + u1[time + 1][x][y]/pow(dt, 2)) + 2*(u2[t - 1][x][y] + u1[time][x][y]/pow(dt, 2)) + u2[t][x][y];
        }
      }
    }
    gettimeofday(&end_section_0, NULL);
    timers->section_0 += (double)(end_section_0.tv_sec-start_section_0.tv_sec)+(double)(end_section_0.tv_usec-start_section_0.tv_usec)/1000000;
  }
  return 0;
}
```

**Comment by FabioLuporini** [comment]
> Generates code with 4 separate time loops.

that's because the second equation (the one after ``src.inject``) does ``u1.dt2``, which needs ``u1[time+1 ...]``, while at the same time the injection, which happens earlier, is trying to write to ``u1[time]`` ; ie, you're asking the compiler to deal with a (so called) WRITE-AFTER-READ.

Perhaps you wanted to inject into ``u1.forward`` ?

**Comment by mloubout** [comment]
>Perhaps you wanted to inject into u1.forward ?

Generates the same 4 separate time loops code.

**Comment by FabioLuporini** [comment]
> Generates the same 4 separate time loops code.

it does not for me (at least in the branch I'm working on, on top of the domain-allocation switch branch). Keep u posted anyway...

**Comment by mloubout** [comment]
So the 4 loops are indeed merged in one in the domain-switch branch, the buffered indices are not processed however like originally (`u2[t + 1][x][y]`  instead of `u2[t1]` and `t1=time%3`)

**Comment by FabioLuporini** [comment]
sorry, forgot to update you: potential fix in ``fix-subdims`` (not opened as a PR yet, it already makes Travis happy though)

**Comment by FabioLuporini** [comment]
pretty sure it's fixed in ``fix-subdims``. Hopefully PR-able soon (as soon as #507 lands)
