### ISSUE TITLE
ModuleNotFoundError: No module named 'yask'

### ISSUE THREAD

**Issue by jaimesouza** [opesci/devito#840]
Hi,

How can I run devito using yask as backend?

I am trying to run the benchmark, using:

`DEVITO_PLATFORM=skx DEVITO_DEBUG_COMPILER=1 DEVITO_AUTOTUNING=aggressive DEVITO_BACKEND=yask DEVITO_OPENMP=1 DEVITO_ARCH=icc DEVITO_LOGGING=DEBUG numactl --cpubind=1 python benchmark.py bench -bm O3 -P acoutic -so 4 -to 2 -d 512 512 512 --tn 1000 -x 1`

But I get the following error:

```
Traceback (most recent call last):
  File "/opt/devito/devito/yask/__init__.py", line 39, in <module>
    import yask as yc
ModuleNotFoundError: No module named 'yask'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "benchmark.py", line 7, in <module>
    from devito import clear_cache, configuration, mode_develop, mode_benchmark, warning
  File "/opt/devito/devito/__init__.py", line 100, in <module>
    init_configuration()
  File "/opt/devito/devito/parameters.py", line 176, in init_configuration
    configuration.initialize()
  File "/opt/devito/devito/parameters.py", line 97, in initialize
    self._updated(k, v)
  File "/opt/devito/devito/parameters.py", line 54, in _updated
    retval = self._update_functions[key](value)
  File "/opt/devito/devito/backends.py", line 139, in init_backend
    set_backend(backend)
  File "/opt/devito/devito/backends.py", line 118, in set_backend
    mod = __import__('devito.%s' % backend, fromlist=['None'])
  File "/opt/devito/devito/yask/__init__.py", line 45, in <module>
    exit("Python YASK compiler bindings")
  File "/opt/devito/devito/yask/__init__.py", line 24, in exit
    raise InvalidOperator("YASK Error [%s]. Exiting..." % emsg)
devito.exceptions.InvalidOperator: YASK Error [Python YASK compiler bindings]. Exiting...
```

Do I have to install yask e set any environment variable?

Regards,

Jaime

**Comment by btrb** [comment]
Hey Jaime,

How have you installed yask?
You could mimic what is done by `travis.yml`.
Check it out:
https://github.com/opesci/devito/blob/master/.travis.yml#L113

For quicker replies, I'd strongly recommend you to use the #yask channel from our slack.

Cheers

**Comment by jaimesouza** [comment]
Hi Lucas,

I have done like travis.yml this time.
It's working well.
Thanks!!
